version: '3'
services: 
  gas:
    build: .
    container_name: 'gas-build'
    tty: true
    volumes: 
      - ".:/workdir"
      - "./.clasprc.json:/root/.clasprc.json"
    working_dir: /workdir


