version: '3'
services: 
  gas:
    build: .
    container_name: 'gas-build'
    tty: true
    working_dir: /workdir
    volumes: 
      - ..:/workdir
      - ../.clasprc.json:/root/.clasprc.json
      # - ../src:/opt/src
      # - ../dist:/opt/dist
